{"name": "Attempted login with valid and invalid credentials -- @1.4 ", "status": "passed", "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1716117598658, "stop": 1716117598716}, {"name": "When I fill in \"username\" with \"standard_user\"", "status": "passed", "start": 1716117598716, "stop": 1716117598846}, {"name": "And I fill in \"Password\" with \"standarduser321\"", "status": "passed", "start": 1716117598846, "stop": 1716117598968}, {"name": "And I press \"Login\"", "status": "passed", "start": 1716117598968, "stop": 1716117599011}, {"name": "Then I should see \"negative\" with this \"Epic sadface: Username and password do not match any user in this service\"", "status": "passed", "start": 1716117599012, "stop": 1716117599045}], "parameters": [{"name": "username", "value": "standard_user"}, {"name": "password", "value": "standarduser321"}, {"name": "message_type", "value": "negative"}, {"name": "message", "value": "Epic sadface: Username and password do not match any user in this service"}], "start": 1716117598657, "stop": 1716117599045, "uuid": "0bbe334b-3ec0-4214-ae4e-af53eb3eff79", "historyId": "8e658f65af7e76b13fc8f2a2e8debbe8", "fullName": "Login: Attempted login with valid and invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}