{"name": "Attempted login with valid and invalid credentials -- @1.6 ", "status": "passed", "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1716117599279, "stop": 1716117599323}, {"name": "When I fill in \"username\" with \"standard_bond\"", "status": "passed", "start": 1716117599324, "stop": 1716117599439}, {"name": "And I fill in \"Password\" with \"secret_sauce\"", "status": "passed", "start": 1716117599439, "stop": 1716117599562}, {"name": "And I press \"Login\"", "status": "passed", "start": 1716117599563, "stop": 1716117599617}, {"name": "Then I should see \"negative\" with this \"Epic sadface: Username and password do not match any user in this service\"", "status": "passed", "start": 1716117599618, "stop": 1716117599631}], "parameters": [{"name": "username", "value": "standard_bond"}, {"name": "password", "value": "secret_sauce"}, {"name": "message_type", "value": "negative"}, {"name": "message", "value": "Epic sadface: Username and password do not match any user in this service"}], "start": 1716117599278, "stop": 1716117599631, "uuid": "f92d1fee-34a3-49c6-94d9-8af20aeabdcd", "historyId": "44e6924ca4f4cb35666ca0aa307b4c45", "fullName": "Login: Attempted login with valid and invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}