{"name": "Attempted login with valid and invalid credentials -- @1.4 ", "status": "passed", "steps": [{"name": "Given I am on the login page", "status": "passed", "start": 1716114862332, "stop": 1716114862416}, {"name": "When I fill in \"username\" with \"standard_user\"", "status": "passed", "start": 1716114862416, "stop": 1716114862571}, {"name": "And I fill in \"Password\" with \"standarduser321\"", "status": "passed", "start": 1716114862572, "stop": 1716114862736}, {"name": "And I press \"Login\"", "status": "passed", "start": 1716114862736, "stop": 1716114862795}, {"name": "Then I should see \"negative\" with this \"Epic sadface: Username and password do not match any user in this service\"", "status": "passed", "start": 1716114862795, "stop": 1716114862813}], "parameters": [{"name": "username", "value": "standard_user"}, {"name": "password", "value": "standarduser321"}, {"name": "message_type", "value": "negative"}, {"name": "message", "value": "Epic sadface: Username and password do not match any user in this service"}], "start": 1716114862331, "stop": 1716114862813, "uuid": "18935db9-79df-4d18-8a64-7ed3b1c61cdc", "historyId": "8e658f65af7e76b13fc8f2a2e8debbe8", "fullName": "Login: Attempted login with valid and invalid credentials", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}